# Server settings 
server: 
  port: 80
  address: 0.0.0.0
# 24 hours
  session:
    timeout: 86400
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    basedir: /
# DATASOURCE
#jdbc:
#  driverLocation: D:\\repo\\mysql\\mysql-connector-java\\5.1.38\\mysql-connector-java-5.1.38.jar
#  driverClass: com.mysql.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=utf-8
#  username: root
#  password: 123456
 
# SPRING PROFILES 
spring:
  aop:
    # Add @EnableAspectJAutoProxy.
    auto: true
    # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
    proxy-target-class: false

  mvc:
    throw-exception-if-no-handler-found: false


  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding:
      enabled: true
      force: true
    # HTTP message conversion
    # Preferred JSON mapper to use for HTTP message conversion. Set to "gson" to force the use of Gson when both it and Jackson are on the classpath.
    converters:
      preferred-json-mapper: gson
  thymeleaf:
    cache: false
    encoding: UTF-8
    enabled: true
    excluded-view-names: jsp/
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    #username: rootsa
    #password: Moses12345
    usedatabase: spring
    backupdir: "d:/backup"
    aabackupcron: "0 0/1 * * * ? *"
    backupcron: "0 0 1 1/1 * ? *"
    validation-query: SELECT 1;
    test-on-borrow: true
    test-while-idle: true
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size:  5
    min-idle: 5
    minimum-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    filters: stat,wall,slf4j
    #proxyFilters: wall2
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;druid.wall.selectWhereAlwayTrueCheck=false;druid.wall.conditionAndAlwayTrueAllow=true
    pool-prepared-statements: true
    max-open-prepared-statements: 20






#  data:
#    solr:
#      host: http://127.0.0.1:8983/solr
#      repositories:
#        enabled: true


  jpa:
    database: MYSQL
    database-platform: MYSQL
    generate-ddl: true
    hibernate:
      # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
      ddl-auto: update
      # ddl-auto: create
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      #hibernate.show_sql: false
      #hibernate.format_sql: false

      # Allows Hibernate to generate SQL optimized for a particular DBMS
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.max_fetch_depth: 3
      hibernate.enable_lazy_load_no_trans: true
      hibernate.jdbc.fetch_size: 50
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: d:/logs2
      hibernate.search.jmx_enabled: true
      hibernate.search.generate_statistics: true
      hibernate.search.lucene_version: LUCENE_CURRENT



# MyBatis 
#mybatis:
#  typeAliasesPackage: com.modou.**.domain
#  mapperLocations: classpath:/com/modou/**/mapper/*.xml
#  configLocation: classpath:/mybatis-config.xml
 
#
#  hornetq:
#    embedded:
#      cluster-password: # LOGGING
#logging:
#  level:
#    com.ibatis: DEBUG
#    org.hibernate.SQL: DEBUG



multipart:
  max-file-size: 20Mb
  max-request-size: 30Mb



security:
  user:
    name: root
    password: Moses12345
management:
  security:
    roles: SUPERUSER
  context-path: /admins



#JMX
#
#management:
#
#  port: 8081
#  address: 127.0.0.1
#  security:
#    enabled: false
#  context-path: /manage


#系统配置
SprKi:
  lucene:
    chinese: false
    init: false
  upload:
    #建议不要修改，否则无法访问到
    savepathroot: ./static/
    savepathchild: /uploaded/
    #访问文件的地址
    accesspath: /uploaded/
    #备份位置
    backupattachpath: d:/backup/attachments/
  editor:
    acl: ROLE_USER