# Server settings 
server: 
  port: 80
  address: localhost


# DATASOURCE 
#jdbc:
#  driverLocation: D:\\repo\\mysql\\mysql-connector-java\\5.1.38\\mysql-connector-java-5.1.38.jar
#  driverClass: com.mysql.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=utf-8
#  username: root
#  password: 123456
 
# SPRING PROFILES 
spring:
  aop:
    # Add @EnableAspectJAutoProxy.
    auto: true
    # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
    proxy-target-class: false

  mvc:
    throw-exception-if-no-handler-found: false



  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding:
      enabled: true
      force: true
    # HTTP message conversion
    # Preferred JSON mapper to use for HTTP message conversion. Set to "gson" to force the use of Gson when both it and Jackson are on the classpath.
    converters:
      preferred-json-mapper: gson
  thymeleaf:
    cache: false
    encoding: UTF-8
    enabled: true
    excluded-view-names: jsp/
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    test-on-borrow: true
    validation-query: SELECT 1;
    test-while-idle: true




  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
      ddl-auto: update
      # ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
      hibernate.enable_lazy_load_no_trans: true



# MyBatis 
#mybatis:
#  typeAliasesPackage: com.modou.**.domain
#  mapperLocations: classpath:/com/modou/**/mapper/*.xml
#  configLocation: classpath:/mybatis-config.xml
 
#
#  hornetq:
#    embedded:
#      cluster-password: # LOGGING
logging:
  level: 
    com.ibatis: DEBUG
    org.hibernate.SQL: DEBUG



#系统配置
SprKi:
  upload:
    savepathroot: ./static/
    savepathchild: /uploaded/
  editor:
    acl: ROLE_USER